"""EU-first leafy crops distributed through the standalone GrowMaster Plant DB."""


_DANDELION_COMMON = {
    "english_name": "Dandelion",
    "botanical_name": "Taraxacum officinale",
    "family": "Asteraceae",
    "category": "Listnata",
    "planting_method": "direct",
    "heat_tolerance": "srednja",
    "cold_tolerance": "visoka",
    "cultivation_methods": "direct",
    "source_name": "Intersemillas EU / Voltz Maraîchage / Prosem",
}

EU_LEAFY_CROPS = [
    {
        **_DANDELION_COMMON,
        "crop": "Regrat",
        "name": "Navadni regrat",
        "days": 55,
        "source_url": "https://www.intersemillas.es/catalogo/cultivos-horticolas/baby-leaf/diente-de-leon/",
        "seed_forms": "navadno seme; približno 1500 semen/g",
        "traits": "Osnovni Taraxacum officinale za liste, rozete in večkratno obiranje.",
        "slovenia_note": "Osnovna kultura. Za gosto mlado listje izberi ločen profil Baby leaf regrat.",
        "days_baby": 30,
        "seed_rate_g_m2": 0.65,
        "seed_spacing_cm": 17.5,
        "row_spacing_cm": 30.0,
        "outdoor_months": "3,4,9,10",
        "protected_months": "2,3,4,9,10,11",
        "planting_calendar_note": "Sej približno 0,5 cm globoko; za kalitev vzdržuj 15–20 °C in enakomerno vlago.",
        "succession_interval_days": 21,
        "calendar_source_url": "https://www.intersemillas.es/catalogo/cultivos-horticolas/baby-leaf/diente-de-leon/",
        "harvest_methods": "outer_leaves,cut_and_regrow",
        "nursery_days": None,
        "direct_sow_extra_days": None,
        "days_outer_leaf": 55,
        "regrowth_interval_min_days": 14,
        "regrowth_interval_max_days": 21,
        "max_regrowth_cuts": 4,
        "days_green_harvest": None,
        "harvest_interval_days": None,
        "harvest_duration_days": None,
        "harvest_profile_note": "Zunanje liste obiraj brez poškodbe rastnega središča.",
        "harvest_source_url": "https://www.intersemillas.es/catalogo/cultivos-horticolas/baby-leaf/diente-de-leon/",
    },
    {
        **_DANDELION_COMMON,
        "crop": "Baby leaf regrat",
        "name": "Baby leaf regrat",
        "days": 30,
        "source_url": "https://www.intersemillas.es/catalogo/cultivos-horticolas/baby-leaf/diente-de-leon/",
        "seed_forms": "navadno seme; približno 1500 semen/g",
        "traits": "Gostejša direktna setev za mlade nežne liste; cut-and-regrow.",
        "slovenia_note": "Profesionalni baby-leaf profil. Setvena norma 5–8 kg/ha (0,5–0,8 g/m²); kalitev 15–20 °C v 7–15 dneh; globina 0,5 cm.",
        "days_baby": 30,
        "seed_rate_g_m2": 0.65,
        "seed_spacing_cm": None,
        "row_spacing_cm": None,
        "outdoor_months": "3,4,9,10",
        "protected_months": "2,3,4,9,10,11",
        "planting_calendar_note": "Jesenska ali zgodnjepomladanska setev; pri baby leafu uporabi gosto setev in enakomerno vlago.",
        "succession_interval_days": 14,
        "calendar_source_url": "https://www.intersemillas.es/catalogo/cultivos-horticolas/baby-leaf/diente-de-leon/",
        "harvest_methods": "baby_leaf,cut_and_regrow",
        "nursery_days": None,
        "direct_sow_extra_days": None,
        "days_outer_leaf": None,
        "regrowth_interval_min_days": 14,
        "regrowth_interval_max_days": 21,
        "max_regrowth_cuts": 4,
        "days_green_harvest": 30,
        "harvest_interval_days": None,
        "harvest_duration_days": None,
        "harvest_profile_note": "Reži mlade liste nad rastnim središčem, da omogočiš ponovno rast.",
        "harvest_source_url": "https://www.intersemillas.es/catalogo/cultivos-horticolas/baby-leaf/diente-de-leon/",
    },
    {
        **_DANDELION_COMMON,
        "crop": "Regrat",
        "name": "Vert de Montmagny",
        "days": 55,
        "source_name": "Voltz Maraîchage / Prosem",
        "source_url": "https://fr-shop.voltz-maraichage.com/semences-conventionnelles/pissenlit",
        "seed_forms": "netretirano seme",
        "traits": "Zgodnja, temno zelena sorta z dobro razrezanimi finimi listi; primerna za sveži trg.",
        "slovenia_note": "Profesionalna evropska sorta pravega regrata Taraxacum officinale.",
        "days_baby": 30,
        "seed_rate_g_m2": None,
        "seed_spacing_cm": 12.5,
        "row_spacing_cm": 32.5,
        "outdoor_months": "5,6,7",
        "protected_months": "3,4,5,9,10",
        "planting_calendar_note": "Voltz navaja setev maj–julij za standardno pridelavo.",
        "succession_interval_days": 21,
        "calendar_source_url": "https://fr-shop.voltz-maraichage.com/semences-conventionnelles/pissenlit",
        "harvest_methods": "baby_leaf,outer_leaves,cut_and_regrow",
        "nursery_days": None,
        "direct_sow_extra_days": None,
        "days_outer_leaf": 55,
        "regrowth_interval_min_days": 14,
        "regrowth_interval_max_days": 21,
        "max_regrowth_cuts": 4,
        "days_green_harvest": None,
        "harvest_interval_days": None,
        "harvest_duration_days": None,
        "harvest_profile_note": "Primerna za mlade ali razvite liste; mogoče tudi blanširanje.",
        "harvest_source_url": "https://fr-shop.voltz-maraichage.com/semences-conventionnelles/pissenlit",
    },
    {
        **_DANDELION_COMMON,
        "crop": "Regrat",
        "name": "A Coeur Plein Amélioré",
        "days": 55,
        "source_name": "Voltz Maraîchage / Prosem",
        "source_url": "https://fr-shop.voltz-maraichage.com/semences-conventionnelles/pissenlit",
        "seed_forms": "netretirano seme",
        "traits": "Goste rozete, srednje zeleni nazobčani listi; produktivna francoska sorta.",
        "slovenia_note": "Profesionalna evropska sorta pravega regrata Taraxacum officinale.",
        "days_baby": 30,
        "seed_rate_g_m2": None,
        "seed_spacing_cm": 12.5,
        "row_spacing_cm": 32.5,
        "outdoor_months": "5,6,7",
        "protected_months": "3,4,5,9,10",
        "planting_calendar_note": "Za standardno pridelavo sej v ogreto zemljo; sorta je primerna tudi za blanširanje.",
        "succession_interval_days": 21,
        "calendar_source_url": "https://www.prosem.fr/graineterie-produits/444/production-conventionnelle-pissenlit",
        "harvest_methods": "baby_leaf,outer_leaves,cut_and_regrow",
        "nursery_days": None,
        "direct_sow_extra_days": None,
        "days_outer_leaf": 55,
        "regrowth_interval_min_days": 14,
        "regrowth_interval_max_days": 21,
        "max_regrowth_cuts": 4,
        "days_green_harvest": None,
        "harvest_interval_days": None,
        "harvest_duration_days": None,
        "harvest_profile_note": "Gosta rozeta omogoča obilno obiranje listov in blanširanje.",
        "harvest_source_url": "https://www.prosem.fr/graineterie-produits/444/production-conventionnelle-pissenlit",
    },
    {
        **_DANDELION_COMMON,
        "crop": "Regrat",
        "name": "Nouvelle",
        "days": 55,
        "source_name": "Prosem",
        "source_url": "https://www.prosem.fr/graineterie-produits/444/production-conventionnelle-pissenlit",
        "seed_forms": "netretirano seme",
        "traits": "Izboljšan tip Vert de Montmagny; bolj enakomeren, pokončen, fino nazobčan in komercialno privlačen.",
        "slovenia_note": "Profesionalna evropska sorta pravega regrata Taraxacum officinale.",
        "days_baby": 30,
        "seed_rate_g_m2": None,
        "seed_spacing_cm": 12.5,
        "row_spacing_cm": 32.5,
        "outdoor_months": "5,6,7",
        "protected_months": "3,4,5,9,10",
        "planting_calendar_note": "Pokončen habitus olajša obiranje in blanširanje.",
        "succession_interval_days": 21,
        "calendar_source_url": "https://www.prosem.fr/graineterie-produits/444/production-conventionnelle-pissenlit",
        "harvest_methods": "baby_leaf,outer_leaves,cut_and_regrow",
        "nursery_days": None,
        "direct_sow_extra_days": None,
        "days_outer_leaf": 55,
        "regrowth_interval_min_days": 14,
        "regrowth_interval_max_days": 21,
        "max_regrowth_cuts": 4,
        "days_green_harvest": None,
        "harvest_interval_days": None,
        "harvest_duration_days": None,
        "harvest_profile_note": "Pokončni fini listi so primerni za kakovostno tržno pridelavo.",
        "harvest_source_url": "https://www.prosem.fr/graineterie-produits/444/production-conventionnelle-pissenlit",
    },
]
