"""Curated Johnny's varieties with a realistic growing window in Slovenia.

The list deliberately groups conventional, organic, pelleted, and treated seed
forms under one variety.  Notes are short factual summaries, not copied product
descriptions.  Source availability and shipping are separate from agronomic
suitability.
"""

from app.planting_calendar import JOHNNYS_VARIETY_CALENDARS


JOHNNYS_SOURCE = "Johnny's Selected Seeds"


def variety(
    crop: str,
    family: str,
    name: str,
    days: int,
    source_url: str,
    traits: str,
    slovenia_note: str,
    *,
    seed_forms: str = "navadno",
    days_baby: int | None = None,
    seed_rate_g_m2: float | None = None,
    seed_spacing_cm: float | None = None,
    row_spacing_cm: float | None = None,
) -> dict:
    return {
        "crop": crop,
        "family": family,
        "category": "Domača",
        "name": name,
        "days": days,
        "source_name": JOHNNYS_SOURCE,
        "source_url": source_url,
        "seed_forms": seed_forms,
        "traits": traits,
        "slovenia_note": slovenia_note,
        "days_baby": days_baby,
        "seed_rate_g_m2": seed_rate_g_m2,
        "seed_spacing_cm": seed_spacing_cm,
        "row_spacing_cm": row_spacing_cm,
    }


JOHNNYS_SLOVENIA_VARIETIES = [
    variety(
        "Rukola", "Brassicaceae", "Astro", 38,
        "https://www.johnnyseeds.com/vegetables/greens/arugula-roquette/astro-organic-salad-arugula-seed-2015G.html",
        "Odprto oprašena solatna rukola; prenaša hladnejše in toplejše razmere.",
        "Primerna za zaporedne setve od pomladi do jeseni ter za neogrevan tunel.",
        seed_forms="navadno, ekološko", days_baby=21, seed_rate_g_m2=2.2,
        seed_spacing_cm=0.5, row_spacing_cm=5.1,
    ),
    variety(
        "Solata", "Asteraceae", "Muir", 50,
        "https://www.johnnyseeds.com/vegetables/lettuce/summer-crisp-lettuce-batavia/muir-organic-lettuce-seed-3881G.59.html",
        "Batavia z dobro odpornostjo proti uhajanju v cvet v vročini.",
        "Zelo uporabna za slovensko poletje; za kalitev v vročini poskrbi za hladna tla.",
        seed_forms="ekološko, ekološko peletirano", seed_spacing_cm=25.0,
        row_spacing_cm=25.0,
    ),
    variety(
        "Solata", "Asteraceae", "Breen", 45,
        "https://www.johnnyseeds.com/vegetables/lettuce/",
        "Kompaktna bronasto rdeča mini rimska solata, primerna tudi za zaščiten prostor.",
        "Primerna za pomladne in jesenske termine ter poletne setve z nekaj senčenja.",
        seed_forms="ekološko, peletirano", seed_spacing_cm=20.0,
        row_spacing_cm=20.0,
    ),
    variety(
        "Solata", "Asteraceae", "Truchas", 47,
        "https://www.johnnyseeds.com/vegetables/lettuce/romaine-lettuce-cos/truchas-organic-lettuce-seed-3880G.html",
        "Temno rdeča kompaktna mini rimska solata z odpornostmi proti pomembnim boleznim.",
        "Primerna za pomlad, jesen in neogrevan tunel; uporabna tudi kot baby leaf.",
        seed_forms="ekološko, ekološko peletirano", days_baby=28,
        seed_spacing_cm=20.0, row_spacing_cm=20.0,
    ),
    variety(
        "Špinača", "Amaranthaceae", "Tragopan", 24,
        "https://www.johnnyseeds.com/growers-library/vegetables/spinach/spinach-varieties-planting-program-comparison-chart.html",
        "Hitro rastoča gladkolistna špinača z obsežno odpornostjo proti peronospori.",
        "Najboljša za hladne pomladne in jesenske termine ter zimsko pridelavo pod zaščito.",
        days_baby=24, seed_rate_g_m2=3.5, seed_spacing_cm=0.7,
        row_spacing_cm=5.1,
    ),
    variety(
        "Špinača", "Amaranthaceae", "Space", 25,
        "https://www.johnnyseeds.com/growers-library/vegetables/spinach/spinach-varieties-planting-program-comparison-chart.html",
        "Gladkolistna špinača srednje hitre rasti z več odpornostmi proti peronospori.",
        "Široko uporabna za pomlad, jesen in hladnejše termine pod zaščito.",
        seed_forms="navadno, ekološko", days_baby=25, seed_rate_g_m2=3.5,
        seed_spacing_cm=0.7, row_spacing_cm=5.1,
    ),
    variety(
        "Špinača", "Amaranthaceae", "Flamingo Improved", 27,
        "https://www.johnnyseeds.com/vegetables/spinach/smooth-leaf-spinach/flamingo-improved-f1-spinach-seed-4568.11.html",
        "Hitro rastoča puščičastolistna špinača z odpornostjo proti več rasam peronospore.",
        "Primerna za hitre pomladne in jesenske baby-leaf turnuse.",
        days_baby=27, seed_rate_g_m2=3.5, seed_spacing_cm=0.7,
        row_spacing_cm=5.1,
    ),
    variety(
        "Korenje", "Apiaceae", "Mokum", 54,
        "https://www.johnnyseeds.com/vegetables/carrots/",
        "Zgodnji hibrid tipa Amsterdam; uporaben za baby korenje in zgodnje šope.",
        "Primeren za zgodnje pomladne setve in zaporedno pridelavo v globokih rahlih tleh.",
        seed_forms="navadno, peletirano", days_baby=36, seed_spacing_cm=2.2,
    ),
    variety(
        "Korenje", "Apiaceae", "Napoli", 58,
        "https://www.johnnyseeds.com/vegetables/carrots/",
        "Zgodnji Nantes, namenjen tudi jesenskim setvam in prezimovanju pod zaščito.",
        "Primeren za jesenski pridelek; v hladnejših krajih naj prezimi v tunelu.",
        seed_forms="navadno, ekološko, peletirano", seed_spacing_cm=2.2,
    ),
    variety(
        "Korenje", "Apiaceae", "Bolero", 75,
        "https://www.johnnyseeds.com/vegetables/carrots/storage-carrots/bolero-f1-carrot-seed-216.html",
        "Nantes za jesensko spravilo in daljše skladiščenje z več bolezenskimi odpornostmi.",
        "Primeren za glavno slovensko sezono in zimsko skladiščenje.",
        seed_forms="navadno, peletirano", seed_spacing_cm=2.2,
    ),
    variety(
        "Rdeča pesa", "Amaranthaceae", "Boro", 50,
        "https://www.johnnyseeds.com/vegetables/beets/round-red-beets/boro-f1-beet-seed-3300.59.html",
        "Zgodnja, prilagodljiva okrogla pesa z močnimi listi in dobro sposobnostjo skladiščenja.",
        "Primerna za pomladne in poletne setve, jesenski pridelek ter zimsko skladiščenje.",
        seed_forms="navadno, ekološko, peletirano", seed_spacing_cm=7.6,
        row_spacing_cm=20.0,
    ),
    variety(
        "Rdeča pesa", "Amaranthaceae", "Zeppo", 50,
        "https://www.johnnyseeds.com/vegetables/beets/round-red-beets/",
        "Enakomerna okrogla pesa z močnimi listi, primerna za šope in baby korene.",
        "Primerna za zaporedne setve od pomladi do poznega poletja.",
        seed_forms="navadno, peletirano", days_baby=40, seed_spacing_cm=7.6,
        row_spacing_cm=20.0,
    ),
    variety(
        "Redkvica", "Brassicaceae", "Rover", 21,
        "https://www.johnnyseeds.com/vegetables/radishes/round-radishes/rover-f1-radish-seed-664.59.html",
        "Zelo zgodnja okrogla redkvica, prilagodljiva in tolerantna na vročinski stres.",
        "Primerna za polje ali neogrevan tunel ter za več zaporednih setev.",
        seed_spacing_cm=2.2, row_spacing_cm=15.0,
    ),
    variety(
        "Redkvica", "Brassicaceae", "Sora", 22,
        "https://www.johnnyseeds.com/vegetables/radishes/round-radishes/",
        "Hitro dozorevajoča okrogla rdeča redkvica z enakomernim terminom spravila.",
        "Primerna za zgodnjo pomlad in jesen; poleti zahteva enakomerno vlago.",
        seed_forms="ekološko", seed_spacing_cm=2.2, row_spacing_cm=15.0,
    ),
    variety(
        "Zelje", "Brassicaceae", "Farao", 65,
        "https://www.johnnyseeds.com/vegetables/cabbage/fresh-market-cabbage/farao-f1-cabbage-seed-2110.53.html",
        "Zgodnje hibridno zelje, ki dobro drži na polju in počasneje poka.",
        "Primerno za zgodnjo in glavno sezono; uspeva v hladnejšem in toplejšem delu leta.",
        seed_spacing_cm=40.0, row_spacing_cm=40.0,
    ),
    variety(
        "Zelje", "Brassicaceae", "Tiara", 63,
        "https://www.johnnyseeds.com/vegetables/cabbage/",
        "Zelo zgodnje sveže zelje kompaktnejše rasti.",
        "Primerno za zgodnje spomladanske saditve in hitro poletno prodajo.",
        seed_spacing_cm=35.0, row_spacing_cm=40.0,
    ),
    variety(
        "Brokoli", "Brassicaceae", "Belstar", 65,
        "https://www.johnnyseeds.com/growers-library/vegetables/broccoli/broc.html",
        "Hibrid za pomladne in poletne saditve z dobro odpornostjo na hlad.",
        "Primeren za večino slovenskih območij od pomladi do zgodnje jeseni.",
        seed_forms="ekološko", seed_spacing_cm=40.0, row_spacing_cm=40.0,
    ),
    variety(
        "Brokoli", "Brassicaceae", "Imperial", 66,
        "https://www.johnnyseeds.com/growers-library/vegetables/broccoli/broc.html",
        "Brokoli z zelo dobro toleranco na vročino.",
        "Primeren za pozno pomladne in poletne termine, ko se hladne sorte slabše obnesejo.",
        seed_spacing_cm=40.0, row_spacing_cm=40.0,
    ),
    variety(
        "Brokoli", "Brassicaceae", "Kariba", 66,
        "https://www.johnnyseeds.com/growers-library/vegetables/broccoli/broc.html",
        "Hladno odporen brokoli za jesensko in zimsko pridelavo.",
        "Primeren za jesensko spravilo in milejše zimske razmere pod zaščito.",
        seed_spacing_cm=40.0, row_spacing_cm=40.0,
    ),
    variety(
        "Cvetača", "Brassicaceae", "Snow Crown", 50,
        "https://www.johnnyseeds.com/vegetables/cauliflower/standard-cauliflower/snow-crown-f1-cauliflower-seed-230.11.html",
        "Zelo zgodnja in prilagodljiva bela cvetača z dobro hladno in toplotno toleranco.",
        "Primerna za slovenski pomladni in jesenski pridelek; izogni se vrhuncu poletne vročine.",
        seed_spacing_cm=40.0, row_spacing_cm=40.0,
    ),
    variety(
        "Koleraba", "Brassicaceae", "Kossak", 80,
        "https://www.johnnyseeds.com/vegetables/kohlrabi/storage-kohlrabi/kossak-f1-kohlrabi-seed-237.html",
        "Velika skladiščna koleraba, ki zahteva večji končni razmik.",
        "Primerna za poletno setev, jesensko spravilo in hladno skladiščenje.",
        seed_forms="navadno, ekološko", seed_spacing_cm=25.0,
        row_spacing_cm=30.0,
    ),
    variety(
        "Japonska repa", "Brassicaceae", "Hakurei", 38,
        "https://www.johnnyseeds.com/vegetables/turnips/hakurei-f1-turnip-seed-706.html",
        "Hitra bela solatna repa, tolerantna na zmeren mraz.",
        "Primerna za setev od zgodnje pomladi do poznega poletja.",
        seed_spacing_cm=5.0, row_spacing_cm=20.0,
    ),
    variety(
        "Koromač", "Apiaceae", "Preludio", 80,
        "https://www.johnnyseeds.com/vegetables/fennel/preludio-organic-f1-fennel-seed-3272G.53.html",
        "Enakomeren čebulni koromač za baby ali polno velikost.",
        "Najprimernejši za poletno sajenje in jesensko spravilo ob krajšanju dneva.",
        seed_forms="ekološko, ekološko peletirano", days_baby=50,
        seed_spacing_cm=15.0, row_spacing_cm=25.0,
    ),
    variety(
        "Por", "Amaryllidaceae", "King Richard", 75,
        "https://www.johnnyseeds.com/growers-library/vegetable-library/leeks/",
        "Zgodnji poletni por, uporaben tudi kot baby por; prenese zmerno do močno slano.",
        "Primeren za zgodnje poletno in jesensko spravilo, ne pa za dolgo prezimovanje.",
        seed_forms="ekološko", seed_spacing_cm=15.0, row_spacing_cm=20.0,
    ),
    variety(
        "Por", "Amaryllidaceae", "Bandit", 120,
        "https://www.johnnyseeds.com/growers-library/vegetable-library/leeks/",
        "Pozni odprto oprašen zimski por.",
        "Primeren za jesensko in zimsko spravilo; v celinski Sloveniji ga zaščiti ob hujšem mrazu.",
        seed_forms="ekološko", seed_spacing_cm=15.0, row_spacing_cm=20.0,
    ),
    variety(
        "Fižol", "Fabaceae", "Provider", 50,
        "https://www.johnnyseeds.com/vegetables/beans/bush-beans/provider-bean-seed-10.56.html",
        "Zgoden nizek stročji fižol z odpornostjo proti mozaičnemu virusu in pepelasti plesni.",
        "Primeren za setev po zadnji slani in zaporedne setve do sredine poletja.",
        seed_spacing_cm=5.0, row_spacing_cm=25.0,
    ),
    variety(
        "Fižol", "Fabaceae", "Fortex", 60,
        "https://www.johnnyseeds.com/vegetables/beans/pole-beans/fortex-bean-seed-34.53.html",
        "Visok stročji fižol z dolgimi stroki; potrebuje oporo.",
        "Primeren za toplo slovensko sezono od konca pomladi do zgodnje jeseni.",
        seed_spacing_cm=7.6, row_spacing_cm=40.0,
    ),
    variety(
        "Grah", "Fabaceae", "Sugar Ann", 51,
        "https://www.johnnyseeds.com/vegetables/peas/snap-peas/sugar-ann-pea-seed-559.32.html",
        "Zelo zgodnji nizek sladkorni grah odprtega opraševanja.",
        "Primeren za zelo zgodnjo pomladno setev in zgodnjo jesensko setev.",
        seed_spacing_cm=5.0, row_spacing_cm=20.0,
    ),
    variety(
        "Grah", "Fabaceae", "Sugar Snap", 58,
        "https://www.johnnyseeds.com/vegetables/peas/snap-peas/",
        "Visok sladkorni grah z daljšim obdobjem obiranja; potrebuje mrežo ali drugo oporo.",
        "Primeren za hladno pomladno sezono; izogni se poletni vročini.",
        seed_forms="navadno, ekološko", seed_spacing_cm=5.0,
        row_spacing_cm=20.0,
    ),
    variety(
        "Paradižnik", "Solanaceae", "Defiant PhR", 65,
        "https://www.johnnyseeds.com/vegetables/tomatoes/slicing-tomatoes/defiant-phr-organic-f1-tomato-seed-2525G.53.html",
        "Zgoden determinanten paradižnik z odpornostmi, med drugim proti krompirjevi plesni.",
        "Primeren za slovensko polje in tunel; zgodnost zmanjša tveganje ob krajši sezoni.",
        seed_forms="navadno, ekološko", seed_spacing_cm=45.0,
        row_spacing_cm=40.0,
    ),
    variety(
        "Paradižnik", "Solanaceae", "Mountain Magic", 66,
        "https://www.johnnyseeds.com/vegetables/tomatoes/cocktail-tomatoes/mountain-magic-organic-f1-tomato-seed-2513G.html",
        "Indeterminanten koktajl paradižnik z visoko odpornostjo proti krompirjevi plesni.",
        "Primeren za polje z oporo ali tunel; odpornost je koristna v vlažnih slovenskih poletjih.",
        seed_forms="navadno, ekološko", seed_spacing_cm=45.0,
        row_spacing_cm=40.0,
    ),
    variety(
        "Paprika", "Solanaceae", "Carmen", 80,
        "https://www.johnnyseeds.com/vegetables/peppers/sweet-peppers/corno-di-toros-organic-f1-corno-di-toro-pepper-seed-corno_di_toros_ps.html",
        "Zgodnja rdeča sladka paprika tipa corno di toro; zelena je uporabna približno pri 60 dneh.",
        "Primerna za tunel in toplejše lege na prostem; za rdečo zrelost potrebuje dolgo toplo sezono.",
        seed_forms="navadno, ekološko", seed_spacing_cm=35.0,
        row_spacing_cm=35.0,
    ),
    variety(
        "Paprika", "Solanaceae", "Escamillo", 80,
        "https://www.johnnyseeds.com/vegetables/peppers/sweet-peppers/corno-di-toros-organic-f1-corno-di-toro-pepper-seed-corno_di_toros_ps.html",
        "Zgodnja rumena sladka paprika tipa corno di toro; zelena je uporabna približno pri 60 dneh.",
        "Primerna za tunel in toplejše lege na prostem; rumena zrelost zahteva dolgo toplo sezono.",
        seed_forms="ekološko", seed_spacing_cm=35.0, row_spacing_cm=35.0,
    ),
    variety(
        "Kumara", "Cucurbitaceae", "Diva", 58,
        "https://www.johnnyseeds.com/vegetables/cucumbers/seedless-and-thin-skinned-cucumbers/diva-treated-cucumber-seed-2198T.11.html",
        "Partenokarpna kumara za polje ali zaščiten prostor; na voljo tudi kot netretirano seme.",
        "Primerna za toplo poletno pridelavo; v tunelu jo loči od opraševalnih sort za plodove brez semen.",
        seed_forms="navadno, tretirano", seed_spacing_cm=35.0,
        row_spacing_cm=40.0,
    ),
    variety(
        "Kumara", "Cucurbitaceae", "Socrates", 52,
        "https://www.johnnyseeds.com/vegetables/cucumbers/seedless-and-thin-skinned-cucumbers/socrates-organic-f1-cucumber-seed-2989G.html",
        "Zgodnja partenokarpna kumara s tanko kožico za tunel ali rastlinjak.",
        "Primerna predvsem za zaščiten prostor; potrebuje topla tla in nočne temperature.",
        seed_forms="ekološko", seed_spacing_cm=35.0, row_spacing_cm=40.0,
    ),
    variety(
        "Bučka", "Cucurbitaceae", "Dunja", 47,
        "https://www.johnnyseeds.com/vegetables/squash/summer-squash/dunja-organic-f1-zucchini-squash-seed-3843G.53.html",
        "Zgodnja zelena bučka z odpornostmi proti pepelasti plesni in več virusom.",
        "Primerna za slovensko poletje na prostem ali za zgodnejši pridelek pod zaščito.",
        seed_forms="ekološko", seed_spacing_cm=60.0, row_spacing_cm=70.0,
    ),
    variety(
        "Zelena", "Apiaceae", "Tango", 80,
        "https://www.johnnyseeds.com/vegetables/celery-and-celeriac/celery/tango-organic-celery-seed-647G.53.html",
        "Prilagodljiva stebelna zelena, ki razmeroma dobro prenaša vročinski ali vodni stres.",
        "Primerna za presajanje spomladi; za kakovostna stebla potrebuje stalno vlago.",
        seed_forms="ekološko, ekološko peletirano", seed_spacing_cm=25.0,
        row_spacing_cm=25.0,
    ),
]

for catalog_variety in JOHNNYS_SLOVENIA_VARIETIES:
    calendar_key = (catalog_variety["crop"], catalog_variety["name"])
    catalog_variety.update(JOHNNYS_VARIETY_CALENDARS[calendar_key])
    if catalog_variety["calendar_source_url"] is None:
        catalog_variety["calendar_source_url"] = catalog_variety["source_url"]
