"""Indian and Nepalese crops requested for the GrowMaster Plant DB."""

TNAU_GARDEN = "https://agritech.tnau.ac.in/horticulture/horti_Landscaping_types%20of%20garden.html"
TNAU_FENUGREEK = "https://agritech.tnau.ac.in/horticulture/horti_spice%20crops_fenugreek.html"
TNAU_GOURDS = "https://www.agritech.tnau.ac.in/farm_innovations/farm_innovations_pandal_veg_e.html"
TNAU_OKRA = "https://agritech.tnau.ac.in/org_farm/orgfarm_bhendi_cultivation.html"
TARO_SOURCE = "https://agritech.tnau.ac.in/org_farm/pdf/Horticulture5_231009_094153.pdf"
ICAR_TORIA = "https://www.icar.gov.in/sites/default/files/2022-09/Rabi-Agro-Advisory-2021-22_0.pdf"
ICAR_TS38 = "https://icar.gov.in/en/field-day-toria-variety-ts-38-organized"
TNAU_OYSTER = "https://agritech.tnau.ac.in/pdf/HORTICULTURE.pdf"
RHS_CORIANDER = "https://www.rhs.org.uk/herbs/coriander/grow-your-own"
JOHNNYS_CRUISER = "https://www.johnnyseeds.com/herbs/cilantro-coriander/cruiser-organic-cilantro-coriander-seed-3755G.32.html"
JOHNNYS_LEISURE = "https://www.johnnyseeds.com/herbs/cilantro-coriander/leisure-cilantro-coriander-seed-3409.11.html"
JOHNNYS_SANTO = "https://prod-na02.johnnyseeds.com/herbs/cilantro-coriander/santo-cilantro-coriander-seed-919.html"
STOKES_CORIANDER = "https://s3.amazonaws.com/pageturnpro2.com/Publications/202311/2593/110179/PDF/133439282584363611_2024_Stokes_Seeds_Catalog_Digital_US.pdf"
IIHR_VARIETY_REGISTRY = "https://nhfqr.iihr.res.in/"


def crop(
    crop_name, name, family, category, days, source, *, method="direct",
    outdoor="5,6", protected="4,5,6", heat="visoka", cold="nizka",
    spacing=30.0, rows=45.0, seed_rate=None, traits, note,
    nursery=None, harvest="full_size", interval=None, duration=None,
    source_name="TNAU/ICAR agronomska priporočila", seed_forms="navadno seme",
):
    return {
        "crop": crop_name, "name": name, "family": family, "category": category,
        "days": days, "source_name": source_name,
        "source_url": source, "seed_forms": seed_forms if method != "vegetative" else "sadni gomolj",
        "traits": traits, "slovenia_note": note, "days_baby": 25 if harvest == "baby_leaf" else None,
        "seed_rate_g_m2": seed_rate, "seed_spacing_cm": spacing, "row_spacing_cm": rows,
        "planting_method": method, "outdoor_months": outdoor, "protected_months": protected,
        "heat_tolerance": heat, "cold_tolerance": cold,
        "planting_calendar_note": note, "succession_interval_days": 14 if harvest in {"leaf", "baby_leaf"} else None,
        "calendar_source_url": source, "cultivation_methods": method,
        "harvest_methods": harvest, "nursery_days": nursery, "direct_sow_extra_days": None,
        "days_outer_leaf": days if harvest == "leaf" else None,
        "regrowth_interval_min_days": 10 if harvest == "leaf" else None,
        "regrowth_interval_max_days": 18 if harvest == "leaf" else None,
        "max_regrowth_cuts": 3 if harvest == "leaf" else None,
        "days_green_harvest": days if harvest in {"green_fruit", "pods"} else None,
        "harvest_interval_days": interval, "harvest_duration_days": duration,
        "harvest_profile_note": note, "harvest_source_url": source,
    }


WARM_NOTE = "Toploljubna južnoazijska kultura; v Sloveniji jo sej oziroma presadi po slani, za zanesljiv pridelek pa uporabi tunel."
COOL_NOTE = "Južnoazijski hladnosezonski tip; v Sloveniji je najzanesljivejši spomladi in jeseni."
CORIANDER_LEAF_NOTE = "Profesionalni listni koriander za gosto direktno setev in sukcesije; prednost imajo počasneje cvetoči tipi, zlasti v toplejšem delu sezone."

SOUTH_ASIAN_REQUESTED_CROPS = [
    crop("Bamija", "Arka Anamika", "Malvaceae", "Indijska", 55, TNAU_OKRA,
         spacing=30, rows=45, traits="Indijska neolesenela okra/bhindi z dolgimi zelenimi stroki.", note=WARM_NOTE,
         harvest="pods", interval=3, duration=60),
    crop("Bamija", "Arka Abhay", "Malvaceae", "Indijska", 58,
         "https://nhfqr.iihr.res.in/OKRA-VARIETY-ARKA-ABHAY.html",
         spacing=30, rows=45, traits="Uradna profesionalna sorta bamije/okre ICAR-IIHR za tržno pridelavo zelenih strokov.",
         note=WARM_NOTE + " Čas do prvega obiranja je konservativna slovenska načrtovalska ocena.",
         harvest="pods", interval=3, duration=60, source_name="ICAR-IIHR – uradni register sort",
         seed_forms="profesionalno seme"),
    crop("Azijska gorčica", "Pusa Sag-1", "Brassicaceae", "Indijska", 40, TNAU_GARDEN,
         outdoor="3,4,8,9,10", protected="2,3,4,9,10,11", heat="srednja", cold="visoka",
         spacing=10, rows=20, seed_rate=0.6, traits="Listna gorčica za saag in mlade liste.", note=COOL_NOTE, harvest="leaf"),
    crop("Palak", "Pusa All Green", "Amaranthaceae", "Indijska", 40, TNAU_GARDEN,
         outdoor="3,4,8,9,10", protected="2,3,4,9,10,11", heat="srednja", cold="visoka",
         spacing=7.5, rows=20, seed_rate=3.0, traits="Indijska gladkolistna špinača/palak za več rezov.", note=COOL_NOTE, harvest="leaf"),
    crop("Palak", "Arka Anupama", "Amaranthaceae", "Indijska", 40,
         "https://nhfqr.iihr.res.in/PALAK-VARIETY-ARKA-ANUPAMA.html",
         outdoor="3,4,8,9,10", protected="2,3,4,9,10,11", heat="srednja", cold="visoka",
         spacing=7.5, rows=20, seed_rate=3.0, traits="Uradna profesionalna sorta palaka ICAR-IIHR za listno pridelavo.",
         note=COOL_NOTE + " Za GrowMaster je 40 dni začetna načrtovalska vrednost, ki jo prilagodi rezultatu na kmetiji.",
         harvest="leaf", source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno seme"),
    crop("Methi", "Indian Fenugreek", "Fabaceae", "Indijska", 30, TNAU_FENUGREEK,
         outdoor="3,4,8,9", protected="2,3,4,9,10", heat="srednja", cold="srednja",
         spacing=5, rows=20, seed_rate=1.2, traits="Fenugreek/methi za list in mlade poganjke.", note=COOL_NOTE, harvest="leaf"),
    crop("Buča", "Arka Chandan", "Cucurbitaceae", "Indijska", 100, TNAU_GARDEN,
         method="transplant", spacing=90, rows=120, traits="Indijski tip buče za zrele plodove.", note=WARM_NOTE, nursery=24),
    crop("Kumara", "Pusa Uday", "Cucurbitaceae", "Indijska", 55, TNAU_GARDEN,
         method="transplant", spacing=35, rows=80, traits="Zgodnja indijska kumara za sveže zelene plodove.", note=WARM_NOTE,
         nursery=21, harvest="green_fruit", interval=3, duration=45),
    crop("Kumara", "Arka Veera", "Cucurbitaceae", "Indijska", 58,
         "https://nhfqr.iihr.res.in/CUCUMBER-VARIETY-ARKA-VEERA.html",
         method="transplant", spacing=35, rows=80,
         traits="Uradna profesionalna indijska sorta kumare ICAR-IIHR za zelene plodove.",
         note=WARM_NOTE + " Čas do prvega pridelka je konservativna slovenska načrtovalska ocena.",
         nursery=21, harvest="green_fruit", interval=3, duration=45,
         source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno seme"),
    crop("Toria", "TS-38", "Brassicaceae", "Indijska", 125, ICAR_TS38,
         outdoor="3,4,8,9", protected="2,3,4,9,10", heat="srednja", cold="visoka",
         spacing=10, rows=30, seed_rate=0.35, traits="Zgodnja oljna ogrščica/toria z 40–45 % olja.", note=COOL_NOTE, harvest="seed"),
    crop("Toria", "T-9", "Brassicaceae", "Indijska", 95, ICAR_TORIA,
         outdoor="3,4,8,9", protected="2,3,4,9,10", heat="srednja", cold="visoka",
         spacing=10, rows=30, seed_rate=0.35, traits="Kratkosezonska toria za zrnje in olje.", note=COOL_NOTE, harvest="seed"),
    crop("Karela", "Small Indian", "Cucurbitaceae", "Indijska", 55, TNAU_GOURDS,
         method="transplant", spacing=75, rows=150, traits="Majhnoplodni, izrazito grenak tip karele.", note=WARM_NOTE,
         nursery=24, harvest="green_fruit", interval=3, duration=60),
    crop("Karela", "Large Indian", "Cucurbitaceae", "Indijska", 60, TNAU_GOURDS,
         method="transplant", spacing=90, rows=150, traits="Velikoplodni indijski tip grenke kumare.", note=WARM_NOTE,
         nursery=24, harvest="green_fruit", interval=3, duration=60),
    crop("Grah", "Arkel", "Fabaceae", "Indijska", 60, TNAU_GARDEN,
         outdoor="2,3,4,8,9", protected="2,3,4,9,10", heat="nizka", cold="visoka",
         spacing=5, rows=30, traits="Zgodnji indijski vrtni grah za sveže stroke.", note=COOL_NOTE,
         harvest="pods", interval=4, duration=21),
    crop("Redkvica", "Pusa Chetki", "Brassicaceae", "Indijska", 45, TNAU_GARDEN,
         outdoor="3,4,5,8,9", protected="2,3,4,9,10", heat="visoka", cold="srednja",
         spacing=10, rows=15, seed_rate=1.0, traits="Toplotno tolerantna indijska bela redkev.", note=COOL_NOTE),
    crop("Fižol", "Arka Komal", "Fabaceae", "Indijska", 55, TNAU_GARDEN,
         spacing=15, rows=45, traits="Indijski nizki stročji fižol za zelene stroke.", note=WARM_NOTE,
         harvest="pods", interval=4, duration=30),
    crop("Lauki", "Pusa Naveen", "Cucurbitaceae", "Indijska", 65, TNAU_GOURDS,
         method="transplant", spacing=90, rows=150, traits="Bottle gourd/lauki z dolgimi svetlo zelenimi plodovi.", note=WARM_NOTE,
         nursery=24, harvest="green_fruit", interval=4, duration=60),
    crop("Lauki", "Arka Ganga F1", "Cucurbitaceae", "Indijska", 65,
         "https://nhfqr.iihr.res.in/BOTTLE-GOURD-HYBRID-F1-ARKA-GANGA.html",
         method="transplant", spacing=90, rows=150,
         traits="Uradni profesionalni F1 hibrid bottle gourd/lauki ICAR-IIHR.",
         note=WARM_NOTE + " Zaradi dolge rasti in potrebe po opori ima pri nas prednost visok tunel.",
         nursery=24, harvest="green_fruit", interval=4, duration=60,
         source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno F1 seme"),
    crop("Rebrasta bučka", "Arka Vikram F1", "Cucurbitaceae", "Indijska", 55,
         "https://nhfqr.iihr.res.in/RIDGE-GOURD-HYBRID-F1-ARKA-VIKRAM.html",
         method="transplant", spacing=75, rows=150,
         traits="Uradni profesionalni F1 hibrid ridge gourd/turai ICAR-IIHR.",
         note=WARM_NOTE + " Vodi jo na opori; 55 dni je začetna načrtovalska ocena za prvi zeleni pridelek.",
         nursery=24, harvest="green_fruit", interval=3, duration=55,
         source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno F1 seme"),
    crop("Indijski jajčevec", "Arka Anand F1", "Solanaceae", "Indijska", 115,
         "https://nhfqr.iihr.res.in/BRINJAL-HYBRID-F1-ARKA-ANAND.html",
         method="transplant", spacing=45, rows=75,
         traits="Uradni profesionalni F1 hibrid brinjala ICAR-IIHR.",
         note=WARM_NOTE + " Za zanesljivo zgodnje in podaljšano obiranje je tunel priporočljiv.",
         nursery=56, harvest="green_fruit", interval=5, duration=70,
         source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno F1 seme"),
    crop("Listni amarant", "Arka Arunima", "Amaranthaceae", "Indijska", 30,
         "https://nhfqr.iihr.res.in/AMARANTHUS-VARIETY-ARKA-ARUNIMA.html",
         outdoor="5,6,7,8", protected="4,5,6,7,8,9", heat="visoka", cold="nizka",
         spacing=5, rows=20, seed_rate=0.5,
         traits="Uradna profesionalna sorta listnega amaranta/chaulai ICAR-IIHR.",
         note="Toploljubna listna kultura; sej v ogreta tla in jo obiraj mlado ali večkrat reži.",
         harvest="leaf", source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno seme"),
    crop("Taro", "Sree Rashmi", "Araceae", "Indijska", 240, TARO_SOURCE,
         method="vegetative", outdoor="5,6", protected="4,5", spacing=45, rows=60,
         traits="Taro/colocasia za užitne gomolje; razmnožuje se s stranskimi gomolji.", note=WARM_NOTE, harvest="tubers"),
    crop("Koriander", "CO-4", "Apiaceae", "Indijska", 40, TNAU_FENUGREEK,
         outdoor="3,4,5,8,9", protected="2,3,4,9,10", heat="srednja", cold="srednja",
         spacing=5, rows=20, seed_rate=0.6, traits="Koriander/dhania za list in seme.", note=COOL_NOTE, harvest="leaf"),
    crop("Koriander", "Arka Isha", "Apiaceae", "Indijska", 45,
         "https://nhfqr.iihr.res.in/CORIENDER-VARIETY-ARKA-ISHA.html",
         outdoor="3,4,5,8,9", protected="2,3,4,9,10", heat="srednja", cold="srednja",
         spacing=1, rows=8, seed_rate=6.0,
         traits="Uradna profesionalna sorta listnega koriandra/dhania ICAR-IIHR.",
         note=CORIANDER_LEAF_NOTE + " Dobavljivost semena za uvoz v EU je treba preveriti ločeno.",
         harvest="leaf", source_name="ICAR-IIHR – uradni register sort", seed_forms="profesionalno seme"),
    crop("Koriander", "Calypso", "Apiaceae", "Zelišča", 50, RHS_CORIANDER,
         outdoor="3,4,5,6,7,8,9", protected="2,3,4,9,10,11", heat="visoka", cold="srednja",
         spacing=1, rows=8, traits="Zelo počasi uhaja v cvet; dolg poletni pridelek in dobra ponovna rast po rezi.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="RHS / profesionalni listni koriander"),
    crop("Koriander", "Cruiser", "Apiaceae", "Zelišča", 52, JOHNNYS_CRUISER,
         outdoor="3,4,5,6,7,8,9", protected="2,3,4,9,10,11", heat="visoka", cold="srednja",
         spacing=1, rows=8, traits="Izenačena, pokončna in počasneje cvetoča sorta z velikimi listi in močnimi stebli; primerna za tržno vezanje.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="Johnny's Selected Seeds"),
    crop("Koriander", "Leisure", "Apiaceae", "Zelišča", 52, JOHNNYS_LEISURE,
         outdoor="3,4,5,6,7,8,9", protected="2,3,4,9,10,11", heat="srednja", cold="srednja",
         spacing=1, rows=8, traits="Standardni profesionalni cilantro z dobro izenačenostjo, okusom in toleranco na uhajanje v cvet.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="Johnny's Selected Seeds"),
    crop("Koriander", "Santo", "Apiaceae", "Zelišča", 52, JOHNNYS_SANTO,
         outdoor="3,4,5,6,7,8,9", protected="2,3,4,9,10,11", heat="srednja", cold="srednja",
         spacing=1, rows=8, traits="Uveljavljen listni in dvonamenski tip za sveže liste ter poznejšo pridelavo semena.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="Johnny's Selected Seeds"),
    crop("Koriander", "Confetti", "Apiaceae", "Zelišča", 50, RHS_CORIANDER,
         outdoor="3,4,5,6,7,8,9", protected="2,3,4,9,10,11", heat="srednja", cold="srednja",
         spacing=1, rows=8, traits="Fino deljeni, dekorativni listi in blažji okus; uporabna specialiteta za premium mešanice in garnish.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="RHS / profesionalni listni koriander"),
    crop("Koriander", "Filtro", "Apiaceae", "Zelišča", 50, RHS_CORIANDER,
         outdoor="3,4,5,6,7,8,9", protected="2,3,4,9,10,11", heat="srednja", cold="srednja",
         spacing=1, rows=8, traits="Bujna listna sorta z obilnim pridelkom aromatičnih listov.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="RHS / profesionalni listni koriander"),
    crop("Koriander", "Advanced Turbo II", "Apiaceae", "Zelišča", 38, STOKES_CORIANDER,
         outdoor="4,5,6,7,8,9", protected="3,4,9,10", heat="visoka", cold="srednja",
         spacing=1, rows=8, traits="Zelo počasi cvetoč, toplotno toleranten profesionalni tip z visoko toleranco na bakterijski ožig listov.",
         note=CORIANDER_LEAF_NOTE, harvest="leaf", source_name="Stokes Seeds"),
    crop("Chichinda", "CO-2", "Cucurbitaceae", "Indijska", 65, TNAU_GOURDS,
         method="transplant", spacing=100, rows=180, traits="Snake gourd/chichinda za dolge mlade zelene plodove na opori.", note=WARM_NOTE,
         nursery=24, harvest="green_fruit", interval=3, duration=60),
    crop("Gobe", "Ostrigar", "Pleurotaceae", "Gobe", 28, TNAU_OYSTER,
         method="indoor_substrate", outdoor="", protected="1,2,3,4,5,6,7,8,9,10,11,12",
         heat="srednja", cold="srednja", spacing=None, rows=None,
         traits="Ostrigar za nadzorovano pridelavo na pasteriziranem substratu.",
         note="Ni poljščina: goji se v čistem, vlažnem in prezračevanem prostoru na inokuliranem substratu.",
         harvest="flushes", interval=7, duration=45),
]
